# Generated by Django 5.2.17 on 2026-09-12 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('registrations', '0004_registration_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('coach', models.CharField(blank=True, max_length=150)),
                ('capacity', models.PositiveSmallIntegerField(default=0, help_text='0 means no limit')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='organization.center')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='organization.club')),
                ('members', models.ManyToManyField(blank=True, related_name='training_groups', to='registrations.registration')),
            ],
            options={
                'ordering': ['club__name_en', 'name_en'],
                'unique_together': {('club', 'name_en')},
            },
        ),
        migrations.CreateModel(
            name='WeeklySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('note', models.CharField(blank=True, max_length=150)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='organization.traininggroup')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('group', 'weekday', 'start_time')},
            },
        ),
    ]
