# Generated by Django 5.2.17 on 2026-09-19 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_traininggroup_weeklysession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='organization.center'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'National administrator'), ('CLUB_OWNER', 'Club president'), ('BRANCH_MANAGER', 'Branch manager')], default='CLUB_OWNER', max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('REGISTRATION_STATUS', 'Registration status changed'), ('REGISTRATION_PAYMENT', 'Payment status changed'), ('REGISTRATION_TRANSFER', 'Member moved to another branch'), ('BRANCH_CREATED', 'Branch created'), ('BRANCH_UPDATED', 'Branch updated'), ('BRANCH_DELETED', 'Branch deleted'), ('ACCOUNT_CREATED', 'Account created'), ('ACCOUNT_UPDATED', 'Account updated'), ('ACCOUNT_DEACTIVATED', 'Account deactivated'), ('ACCOUNT_REACTIVATED', 'Account reactivated'), ('PASSWORD_RESET', 'Password reset')], max_length=24)),
                ('target', models.CharField(max_length=200)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='organization.center')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='organization.club')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
