# Generated by Django 5.2.17 on 2026-09-28 16:26

import organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_userprofile_center_alter_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='open_categories',
            field=models.JSONField(default=organization.models.all_category_codes),
        ),
    ]
