# Generated by Django 5.2.17 on 2026-09-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_center_open_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('REGISTRATION_STATUS', 'Registration status changed'), ('REGISTRATION_PAYMENT', 'Payment status changed'), ('REGISTRATION_TRANSFER', 'Member moved to another branch'), ('REGISTRATION_DELETED', 'Registration deleted'), ('BRANCH_CREATED', 'Branch created'), ('BRANCH_UPDATED', 'Branch updated'), ('BRANCH_DELETED', 'Branch deleted'), ('ACCOUNT_CREATED', 'Account created'), ('ACCOUNT_UPDATED', 'Account updated'), ('ACCOUNT_DEACTIVATED', 'Account deactivated'), ('ACCOUNT_REACTIVATED', 'Account reactivated'), ('PASSWORD_RESET', 'Password reset')], max_length=24),
        ),
    ]
