# Generated by Django 5.2.17 on 2026-09-29 22:59

import community.models
import django.core.validators
import organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_activity_registration_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='letterhead_lines',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=community.models.PublicMediaStorage(), upload_to=organization.models.club_logo_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), organization.models.validate_logo_size]),
        ),
        migrations.AddField(
            model_name='club',
            name='logo_secondary',
            field=models.ImageField(blank=True, null=True, storage=community.models.PublicMediaStorage(), upload_to=organization.models.club_logo_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), organization.models.validate_logo_size]),
        ),
    ]
