# Generated by Django 5.2.17 on 2026-08-13 15:43

import django.core.validators
import django.db.models.deletion
import registrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('latin_full_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('education_level', models.CharField(blank=True, max_length=150)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('SENIOR', 'Seniors'), ('VETERAN', 'Veterans'), ('JUNIOR', 'Juniors'), ('CADET', 'Cadets'), ('MINIME', 'Minimes'), ('BENJAMIN', 'Benjamins'), ('POUSSIN', 'Poussins'), ('MINIBAD', 'Minibad')], editable=False, max_length=10)),
                ('is_minor', models.BooleanField(editable=False)),
                ('age_at_registration', models.PositiveSmallIntegerField(editable=False)),
                ('parent_name', models.CharField(blank=True, max_length=200)),
                ('parent_id_type', models.CharField(blank=True, choices=[('CNI', 'National ID card'), ('PERMIS', 'Driving license')], max_length=10)),
                ('parent_id_number', models.CharField(blank=True, max_length=50)),
                ('parent_id_issue_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=10)),
                ('season', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label_ar', models.CharField(max_length=200)),
                ('label_en', models.CharField(max_length=200)),
                ('label_vi', models.CharField(max_length=200)),
                ('applies_to', models.CharField(choices=[('ALL', 'All candidates'), ('MINOR', 'Minors only'), ('MAJOR', 'Adults only')], default='ALL', max_length=5)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_season', models.CharField(default='2025/2026', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=registrations.models.upload_to_registration, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registrations.registration')),
                ('required_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registrations.requireddocument')),
            ],
            options={
                'unique_together': {('registration', 'required_document')},
            },
        ),
    ]
