# Generated by Django 5.2.17 on 2026-09-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='closed_message_ar',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='closed_message_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='closed_message_vi',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registrations_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='key',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
