# Generated by Django 5.2.17 on 2026-09-11 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('registrations', '0002_sitesettings_closed_message_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='organization.center'),
        ),
        migrations.AddField(
            model_name='registration',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='organization.club'),
        ),
    ]
