# Generated by Django 5.2.17 on 2026-10-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_registration_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='decision_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='decision_email_status',
            field=models.CharField(blank=True, choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('NO_EMAIL', 'No address on file')], max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='registration',
            name='language',
            field=models.CharField(choices=[('ar', 'العربية'), ('en', 'English'), ('vi', 'Tiếng Việt')], default='ar', max_length=2),
        ),
        migrations.AddField(
            model_name='registration',
            name='rejection_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('INCOMPLETE', 'Incomplete file'), ('UNREADABLE', 'Documents unreadable'), ('MISMATCH', 'Information does not match the documents'), ('NO_PLACE', 'No place left in this category'), ('DUPLICATE', 'Duplicate registration'), ('OTHER', 'Other')], max_length=12),
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='file_kind',
            field=models.CharField(choices=[('SCAN_PDF', 'Scanned PDF'), ('IMAGE', 'Image (JPG or PNG)')], default='SCAN_PDF', max_length=10),
        ),
    ]
