# Generated by Django 5.2.17 on 2026-09-07 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('COMBAT', 'منازلة - Combat'), ('TECHNIQUE', 'تقني - Technique')], max_length=10)),
                ('season', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('MIXED', 'Mixed')], default='MALE', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=15)),
                ('weight_class', models.CharField(blank=True, choices=[('M46_50', '46 - 50 kg'), ('M50_55', '50 - 55 kg'), ('M55_60', '55 - 60 kg'), ('M60_65', '60 - 65 kg'), ('M65_70', '65 - 70 kg'), ('M70_75', '70 - 75 kg'), ('M75_80', '75 - 80 kg'), ('M80_85', '80 - 85 kg'), ('M85_90', '85 - 90 kg'), ('M90_PLUS', '+90 kg'), ('F44_48', '44 - 48 kg'), ('F48_52', '48 - 52 kg'), ('F52_56', '52 - 56 kg'), ('F56_60', '56 - 60 kg'), ('F60_65', '60 - 65 kg'), ('F65_70', '65 - 70 kg'), ('F70_75', '70 - 75 kg'), ('F75_PLUS', '+75 kg')], max_length=20)),
                ('rounds_per_match', models.PositiveSmallIntegerField(default=3)),
                ('technique_event', models.CharField(blank=True, choices=[('QUYEN_PRESCRIBED', 'Quyen "quy định" — prescribed form'), ('FREESTYLE_BAREHAND', 'Free style — bare hand'), ('FREESTYLE_LONG_WEAPON', 'Free style — long weapon'), ('FREESTYLE_SHORT_WEAPON', 'Free style — short weapon'), ('FREESTYLE_SOFT_WEAPON', 'Free style — soft weapon'), ('GROUP_QUYEN_BAREHAND', 'Group quyen "tập thể" — bare hand'), ('GROUP_QUYEN_WEAPON', 'Group quyen "binh khí tập thể" — weapons'), ('DEMO_COMBAT_BAREHAND', 'Demonstration combat — bare hand'), ('DEMO_COMBAT_WEAPON', 'Demonstration combat — weapons'), ('DUONG_SINH', 'Dưỡng sinh')], max_length=30)),
                ('prescribed_form', models.CharField(blank=True, max_length=100)),
                ('judge_count', models.PositiveSmallIntegerField(default=3)),
                ('scoring_mode', models.CharField(choices=[('TRIMMED', 'Drop highest and lowest, average the rest'), ('AVERAGE', 'Average of all judges')], default='TRIMMED', max_length=10)),
                ('max_score', models.DecimalField(decimal_places=2, default=10, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('club', models.CharField(blank=True, max_length=200)),
                ('seed', models.PositiveSmallIntegerField(default=0, help_text='1 = top seed; 0 = unseeded')),
                ('withdrawn', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.competition')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_entries', to='registrations.registration')),
            ],
            options={
                'ordering': ['seed', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('position', models.PositiveSmallIntegerField(help_text='Index of this match within its round')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('BYE', 'Bye — advanced without fighting')], default='PENDING', max_length=10)),
                ('current_round', models.PositiveSmallIntegerField(default=1)),
                ('next_slot', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.competition')),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='competitions.match')),
                ('participant_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_a', to='competitions.participant')),
                ('participant_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_b', to='competitions.participant')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='competitions.participant')),
            ],
            options={
                'ordering': ['round_number', 'position'],
                'unique_together': {('competition', 'round_number', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Running order')),
                ('form_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('LIVE', 'Live'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='competitions.competition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='competitions.participant')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('competition', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='ScoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('POINT', 'Point'), ('PENALTY', 'Penalty'), ('WARNING', 'Warning')], default='POINT', max_length=10)),
                ('points', models.SmallIntegerField(default=1, help_text='Negative for penalties against this competitor')),
                ('technique', models.CharField(blank=True, max_length=100)),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_events', to='competitions.match')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_events', to='competitions.participant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JudgeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_name', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judge_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_scores', to='competitions.performance')),
            ],
            options={
                'ordering': ['judge_name', 'id'],
                'unique_together': {('performance', 'judge_name')},
            },
        ),
    ]
